# Generated by Django 5.0 on 2025-02-24 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('police_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('mail_id', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.district')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.login')),
            ],
            options={
                'db_table': 'tbl_police_station',
            },
        ),
    ]
