# Generated by Django 5.0 on 2025-02-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0002_policestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='login',
        ),
    ]
