# Generated by Django 5.0 on 2025-02-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0003_remove_policestation_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('police_officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('mail_id', models.CharField(max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('proof', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.district')),
            ],
            options={
                'db_table': 'tbl_police_officer',
            },
        ),
    ]
