# Generated by Django 5.0 on 2025-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0004_policeofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
