# Generated by Django 5.0 on 2025-02-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0005_policeofficer_date_of_birth_policeofficer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.login'),
        ),
    ]
