# Generated by Django 5.0 on 2025-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0006_policeofficer_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeofficer',
            old_name='login_id',
            new_name='login',
        ),
    ]
