# Generated by Django 5.0 on 2025-02-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0007_rename_login_id_policeofficer_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='police_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation'),
        ),
    ]
