# Generated by Django 5.0 on 2025-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0008_policeofficer_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='p_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
