# Generated by Django 5.0 on 2025-02-25 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0009_policeofficer_p_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('complaint_text', models.TextField()),
                ('crime_datetime', models.DateTimeField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_district', to='ctapp.district')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policestation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.userinfo')),
            ],
            options={
                'db_table': 'tbl_crime',
            },
        ),
    ]
