# Generated by Django 5.0 on 2025-02-25 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='police_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policeofficer'),
        ),
    ]
