# Generated by Django 5.0 on 2025-02-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0012_crime_police_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeUpdates',
            fields=[
                ('crime_updates_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_updates', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctapp.crime')),
                ('police_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctapp.policeofficer')),
            ],
            options={
                'db_table': 'tbl_crime_updates',
            },
        ),
    ]
