# Generated by Django 5.0 on 2025-02-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0013_crimeupdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimeupdates',
            old_name='crime_id',
            new_name='crime',
        ),
    ]
