# Generated by Django 5.0 on 2025-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0014_rename_crime_id_crimeupdates_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='crimeupdates',
            name='crime_updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
