# Generated by Django 5.0 on 2025-03-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0016_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimeupdates',
            name='filedoc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
