# Generated by Django 5.0 on 2025-03-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0017_crimeupdates_filedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeupdates',
            name='filedoc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
